services:
  - type: web
    name: stock-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.8
    plan: free
    autoDeploy: true
